version: '2.0'
services:
  bot:
    image: target/flottbot:latest
    entrypoint: >
      /bin/sh -c "./flottbot"
    volumes:
    - $PWD/config:/config
    environment:
        - SLACK_TOKEN
        - SLACK_WORKSPACE_TOKEN
        - SLACK_VERIFICATION_TOKEN
    expose:
        - "5004"
