name: darebot
cli: false
chat_application: slack
slack_token: ${SLACK_TOKEN}                                    # OAuth & Permissions > Bot User OAuth Access Token
slack_verification_token: ${SLACK_VERIFICATION_TOKEN}          # App credentials > Verification Token
slack_workspace_token: ${SLACK_WORKSPACE_TOKEN}                # OAuth & Permissions > OAuth Access Token

slack_events_callback_path: /slack_events/v1/events
slack_interactions_callback_path: /slack_events/v1/interactions
